# Generated by Django 2.1.3 on 2018-11-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_dashboards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='dashboards',
        ),
    ]
