# Generated by Django 2.1.3 on 2018-11-14 23:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('create_date', models.DateField(default=datetime.datetime(2018, 11, 14, 23, 44, 16, 256154, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('board', models.ForeignKey(on_delete='cascade', to='dashboard.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=280)),
                ('create_date', models.DateField(default=datetime.datetime(2018, 11, 14, 23, 44, 16, 262398, tzinfo=utc))),
                ('column', models.ForeignKey(on_delete='cascade', to='dashboard.Column')),
            ],
        ),
    ]
