# Generated by Django 2.1.3 on 2018-11-19 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 19, 0, 55, 59, 355012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 19, 0, 55, 59, 382118, tzinfo=utc)),
        ),
    ]
