# Generated by Django 2.1.3 on 2018-11-19 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181119_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 19, 2, 18, 2, 695031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 19, 2, 18, 2, 711876, tzinfo=utc)),
        ),
    ]
