# Generated by Django 2.1.3 on 2018-11-19 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181119_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 19, 2, 29, 48, 183760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 19, 2, 29, 48, 200160, tzinfo=utc)),
        ),
    ]
