# Generated by Django 2.1.3 on 2018-11-19 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181119_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 19, 3, 26, 52, 71976, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 19, 3, 26, 52, 89111, tzinfo=utc)),
        ),
    ]
