# Generated by Django 2.1.3 on 2018-11-25 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_team_dashboards'),
        ('dashboard', '0006_auto_20181119_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='team',
            field=models.ForeignKey(default=1, on_delete='cascade', to='team.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 16, 42, 49, 469013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 16, 42, 49, 470006, tzinfo=utc)),
        ),
    ]
