# Generated by Django 2.1.3 on 2018-11-29 03:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20181125_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 29, 3, 9, 27, 548586, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='column',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 29, 3, 9, 27, 549601, tzinfo=utc)),
        ),
    ]
